#!/usr/bin/env bash

REPO_NAME="$1"
OPT_DEST="$2"

if [[ -z "$OPT_DEST" ]]; then 
    git clone https://github.com/linmjie/"$REPO_NAME".git
else
    git clone https://github.com/linmjie/"$REPO_NAME".git "$OPT_DEST"
fi
